language: python

python:
  - '3.6'

cache: pip
install:
  - pip install cython # strange dependency behavior for arctic
  - pip install git+https://github.com/manahl/arctic.git
  - pip install -r requirements.txt
script:
  - pytest